name: superBAR
main: FaigerSYS\superBAR\superBAR
version: 1.6.5-1
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: FaigerSYS
description: "Just good and customizable HUD"
website: "https://github.com/FaigerSYS"

commands:
 superbar:
  description: "superBAR command"
  aliases: [sb, supbar, sbar]
  permission: "superbar.cmd"

permissions:
 superbar.use:
  default: true
  description: "Use HUD (You can see HUD)"
 superbar.cmd:
  default: true
  description: "Use superBAR commands"
 superbar.help:
  default: true
  description: "Use superBAR help"
 superbar.switch:
  default: true
  description: "Enable/Disable HUD for you"
 superbar.change:
  default: op
  description: "Change settings via command"
 superbar.reload:
  default: op
  description: "Reload settings"
